charts/am-role-assignment-batch-service/Chart.yaml
charts/am-role-assignment-batch-service/requirements.yaml
charts/am-role-assignment-batch-service/values.preview.template.yaml
charts/am-role-assignment-batch-service/values.yaml
src/main/java/uk/gov/hmcts/reform/roleassignmentbatch/RoleAssignmentBatchApplication.java

Initial checkin for the batch service.

---

build.gradle
src/test/java/uk/gov/hmcts/reform/roleassignmentbatch/RoleAssignmentBatchApplicationTests.java

AM-940: Cleaning suppressions.xml

---

build.gradle

Fixing the gradle dependencies.

---

build.gradle

Suppressing the dependencies.
```
[ ] Yes
[x] No
```

Upgrading the dependency check plugin.

---

charts/am-role-assignment-batch-service/Chart.yaml
charts/am-role-assignment-batch-service/requirements.yaml

test version upgrade
```
[ ] Yes
[ ] No
```

test version upgrade

---

Jenkinsfile_CNP

https://tools.hmcts.net/jira/browse/AM-1116
```
[ ] Yes
[X] No
```

Add script to sync branches with master

---

Jenkinsfile_CNP

https://tools.hmcts.net/jira/browse/AM-1137
```
[ ] Yes
[X] No
```

Commit branch sync changes

---

build.gradle
charts/am-role-assignment-batch-service/Chart.yaml

https://tools.hmcts.net/jira/browse/AM-1272
```
[ ] Yes
[X] No
```

Update job chart version

---

README.md

https://tools.hmcts.net/jira/browse/AM-1312
Added the read me file
```
[ ] Yes
[x] No
```

added the read me file

---

.gitignore
build.gradle
config/owasp/suppressions.xml

https://tools.hmcts.net/jira/browse/AM-1268

CVE clean up

---

build.gradle
gradle/wrapper/gradle-wrapper.properties
src/main/resources/application.yaml

Updating the batch size.

---

src/main/java/uk/gov/hmcts/reform/roleassignmentbatch/RoleAssignmentBatchApplication.java

Fixing the secret issue.
```
[ ] Yes
[x] No
```

updating the debug-distoless image.

---

build.gradle
charts/am-role-assignment-batch-service/Chart.yaml
charts/am-role-assignment-batch-service/values.preview.template.yaml
charts/am-role-assignment-batch-service/values.yaml
src/integrationTest/java/uk/gov/hmcts/reform/roleassignment/BaseTest.java
src/main/java/uk/gov/hmcts/reform/roleassignmentbatch/RoleAssignmentBatchApplication.java
src/main/resources/application.yaml
src/main/resources/bootstrap.yaml

Fixing the vault issue.

---

Dockerfile
src/main/java/uk/gov/hmcts/reform/roleassignmentbatch/RoleAssignmentBatchApplication.java

Reverting the distro.

---

src/main/java/uk/gov/hmcts/reform/roleassignmentbatch/config/AuditSkipListener.java
src/main/java/uk/gov/hmcts/reform/roleassignmentbatch/config/BatchConfig.java
src/main/java/uk/gov/hmcts/reform/roleassignmentbatch/config/NotificationListener.java
src/main/java/uk/gov/hmcts/reform/roleassignmentbatch/domain/model/enums/AuditOperationType.java
src/main/java/uk/gov/hmcts/reform/roleassignmentbatch/task/ValidationTasklet.java
src/main/java/uk/gov/hmcts/reform/roleassignmentbatch/util/Constants.java

https://tools.hmcts.net/jira/browse/AM-1484
Validating ccd users
```
[ ] Yes
[ X] No
```

Am 1484 validation1

---

src/main/java/uk/gov/hmcts/reform/roleassignmentbatch/config/BatchConfig.java
src/main/java/uk/gov/hmcts/reform/roleassignmentbatch/task/RenameTablesPostMigration.java
src/main/java/uk/gov/hmcts/reform/roleassignmentbatch/task/ReplicateTablesTasklet.java
src/main/java/uk/gov/hmcts/reform/roleassignmentbatch/util/Constants.java

https://tools.hmcts.net/jira/browse/AM-1497
index and constraints mapping
```
[ ] Yes
[X ] No
```

add indexing for the tables

---

src/main/java/uk/gov/hmcts/reform/roleassignmentbatch/ApplicationParams.java
src/main/java/uk/gov/hmcts/reform/roleassignmentbatch/config/BatchConfig.java
src/main/java/uk/gov/hmcts/reform/roleassignmentbatch/config/ConfigurationBeans.java
src/main/java/uk/gov/hmcts/reform/roleassignmentbatch/config/JobRunnableDecider.java
src/main/java/uk/gov/hmcts/reform/roleassignmentbatch/rowmappers/CcdViewRowMapper.java
src/main/java/uk/gov/hmcts/reform/roleassignmentbatch/task/RenameTablesPostMigration.java
src/main/java/uk/gov/hmcts/reform/roleassignmentbatch/task/ValidationTasklet.java

split ccd to am job

---

build.gradle
src/main/java/uk/gov/hmcts/reform/roleassignmentbatch/config/BatchConfig.java
src/main/java/uk/gov/hmcts/reform/roleassignmentbatch/config/EmailConfiguration.java
src/main/java/uk/gov/hmcts/reform/roleassignmentbatch/config/SendGridConfig.java
src/main/java/uk/gov/hmcts/reform/roleassignmentbatch/exception/EmailSendFailedException.java
src/main/java/uk/gov/hmcts/reform/roleassignmentbatch/service/EmailService.java
src/main/java/uk/gov/hmcts/reform/roleassignmentbatch/service/EmailServiceImpl.java
src/main/java/uk/gov/hmcts/reform/roleassignmentbatch/task/AfterMigration.java
src/main/java/uk/gov/hmcts/reform/roleassignmentbatch/task/BeforeMigration.java
src/main/java/uk/gov/hmcts/reform/roleassignmentbatch/util/Constants.java
src/main/resources/application.yaml
src/main/resources/mail/email.html

https://tools.hmcts.net/jira/browse/AM-1500
Sendgrid Email functionality integration.
```
[ ] Yes
[x] No
```

Am 1500 sendgrid

---

src/integrationTest/java/uk/gov/hmcts/reform/roleassignmentbatch/CcdToRasBatchJobIntegrationTest.java
src/integrationTest/java/uk/gov/hmcts/reform/roleassignmentbatch/RoleAssignmentBatchJobIntegrationTest.java
src/integrationTest/resources/application-test.yaml
src/main/java/uk/gov/hmcts/reform/roleassignmentbatch/domain/model/EmailData.java
src/main/java/uk/gov/hmcts/reform/roleassignmentbatch/service/EmailService.java
src/main/java/uk/gov/hmcts/reform/roleassignmentbatch/service/EmailServiceImpl.java
src/main/java/uk/gov/hmcts/reform/roleassignmentbatch/task/AfterMigration.java
src/main/java/uk/gov/hmcts/reform/roleassignmentbatch/task/BeforeMigration.java
src/main/java/uk/gov/hmcts/reform/roleassignmentbatch/task/DeleteExpiredRecords.java
src/main/java/uk/gov/hmcts/reform/roleassignmentbatch/task/RenameTablesPostMigration.java
src/main/java/uk/gov/hmcts/reform/roleassignmentbatch/task/ValidationTasklet.java
src/main/java/uk/gov/hmcts/reform/roleassignmentbatch/util/Constants.java
src/main/resources/mail/delete-count.html
src/main/resources/mail/recon-email.html
src/test/java/uk/gov/hmcts/reform/roleassignmentbatch/task/DeleteExpiredRecordsTest.java

AM-1459
Email functionality for expired records.
```
[ ] Yes
[x] No
```

Am 1532 delete expired mail

---

.gitignore
src/main/resources/application.yaml

https://tools.hmcts.net/jira/browse/AM-1585
Add application.yaml file after fixing the SendGrid issue.
```
[ ] Yes
[X] No
```

Add application.yaml file

---

charts/am-role-assignment-batch-service/Chart.yaml

https://tools.hmcts.net/jira/browse/AM-1596
Updating the Helm chart version.
```
[ ] Yes
[x] No
```

Updating the Helm chart version.

---

infrastructure/terraform.tf

Updating the terraform.tf

---

charts/am-role-assignment-batch-service/Chart.yaml
charts/am-role-assignment-batch-service/values.yaml

Removing the schedule from application
```
[ ] Yes
[x] No
```

Removing the schedule from application

---

charts/am-role-assignment-batch-service/Chart.yaml
charts/am-role-assignment-batch-service/values.yaml
src/main/java/uk/gov/hmcts/reform/roleassignmentbatch/service/EmailServiceImpl.java

https://tools.hmcts.net/jira/browse/AM-1596
Adding the env name to Emails.
```
[ ] Yes
[x] No
```

Added the env name to emails.

---

src/main/java/uk/gov/hmcts/reform/roleassignmentbatch/config/ConfigurationBeans.java
src/main/java/uk/gov/hmcts/reform/roleassignmentbatch/domain/model/enums/CcdCaseUser.java
src/main/java/uk/gov/hmcts/reform/roleassignmentbatch/domain/model/enums/ReconQuery.java
src/main/java/uk/gov/hmcts/reform/roleassignmentbatch/processors/EntityWrapperProcessor.java
src/main/java/uk/gov/hmcts/reform/roleassignmentbatch/rowmappers/CcdViewRowMapper.java
src/main/java/uk/gov/hmcts/reform/roleassignmentbatch/service/ReconciliationDataService.java
src/test/java/uk/gov/hmcts/reform/roleassignmentbatch/helper/TestDataBuilder.java

https://tools.hmcts.net/jira/browse/AM-1596
Change CaseTypeId to CaseType.
```
[ ] Yes
[x] No
```

Change CaseTypeId to CaseType.

---

CODEOWNERS
src/integrationTest/java/uk/gov/hmcts/reform/roleassignmentbatch/CcdToRasBatchJobIntegrationTest.java
src/main/java/uk/gov/hmcts/reform/roleassignmentbatch/config/BatchConfig.java
src/main/java/uk/gov/hmcts/reform/roleassignmentbatch/config/JobRunnableDecider.java
src/main/java/uk/gov/hmcts/reform/roleassignmentbatch/domain/model/enums/FlagsEnum.java
src/main/java/uk/gov/hmcts/reform/roleassignmentbatch/task/SetupDbFlags.java
src/main/java/uk/gov/hmcts/reform/roleassignmentbatch/util/Constants.java
src/test/java/uk/gov/hmcts/reform/roleassignmentbatch/launchdarkly/FeatureConditionEvaluatorTest.java

AM-1618
AM-1618: Create additional DB based flag for enabling the migration
```
[ ] Yes
[x] No
```

AM-1618: Create additional DB based flag for enabling the migration

---

Jenkinsfile_nightly_disabled
build.gradle
config/fortify-client.properties

https://tools.hmcts.net/jira/browse/AM-1607
Add fortify implementation
```
[ ] Yes
[X] No
```

Add fortify implementation

---

build.gradle
charts/am-role-assignment-batch-service/Chart.yaml
charts/am-role-assignment-batch-service/values.aat.template.yaml
charts/am-role-assignment-batch-service/values.yaml
config/owasp/suppressions.xml

https://tools.hmcts.net/confluence/display/RSTR/CHG5006041+-+PRD+and+AM+Postgress+Databases+Upgrade+to+v11+Release+Implementation+Plan
```
[ ] Yes
[X] No
```

Update configurations to point to v1 DB

---

build.gradle
config/owasp/suppressions.xml

Fixing the CVE's
```
[ ] Yes
[x] No
```

Fixing the CVE's

---

build.gradle

Fixing the CVE.
```
[ ] Yes
[x] No
```

Fixing the CVE.

---

charts/am-role-assignment-batch-service/Chart.yaml
charts/am-role-assignment-batch-service/values.preview.template.yaml
charts/am-role-assignment-batch-service/values.yaml

added JBS database params for aat

---

Jenkinsfile_CNP
Jenkinsfile_nightly

NA
Enable nightly build and implement fortify scan
```
[ ] Yes
[X] No
```

Enable nightly build and implement fortify

---

build.gradle

NA
Add fortify client library reference
```
[ ] Yes
[X] No
```

Add fortify client library reference

---

src/integrationTest/resources/application-test.yaml

updated the config as per fortify

---

src/main/java/uk/gov/hmcts/reform/roleassignmentbatch/config/BatchConfig.java

disabling the JBS tasklet
```
[ ] Yes
[x] No
```

disabling the JBS tasklet

---

build.gradle
src/main/java/uk/gov/hmcts/reform/roleassignmentbatch/config/BatchConfig.java
src/main/java/uk/gov/hmcts/reform/roleassignmentbatch/task/EmptyTask.java

Disable jbs integration

---

charts/am-role-assignment-batch-service/Chart.yaml
charts/am-role-assignment-batch-service/values.yaml

removed the JBS variable to avoid vault mounting issue
```
[ ] Yes
[x] No
```

removed the JBS variable to avoid vault mounting issue

---

build.gradle

https://tools.hmcts.net/jira/browse/AM-2024
```
[ ] Yes
[x] No
```

Fixed the spring security and log jar cve

---

build.gradle

added missing sl4j dependency for printing logs
```
[ ] Yes
[ X] No
```

adding dependency for enabling logs

---

charts/am-role-assignment-batch-service/Chart.yaml

Updated the chart version

---

charts/am-role-assignment-batch-service/Chart.yaml

Am 2066 java upgrade

---

build.gradle
gradle/wrapper/gradle-wrapper.properties
src/integrationTest/java/uk/gov/hmcts/reform/roleassignmentbatch/BaseTest.java

https://tools.hmcts.net/jira/browse/AM-2068
Gradle upgrade to 7.4.1
```
[ ] Yes
[ X] No
```

gradle upgrade to 7.4.1

---

build.gradle

Updated postgresql dependency

---

build.gradle
config/owasp/suppressions.xml

CVE fix 21 04 ras batch

---

config/owasp/suppressions.xml

Spring-try cve fix
```
[ ] Yes
[ X] No
```

cve suppress

---

Dockerfile
build.gradle

https://tools.hmcts.net/jira/browse/AM-2137
Upgrading to `Java 17`
```
[ ] Yes
[x] No
```

AM-2137: Upgrading to Java 17

---

build.gradle
charts/am-role-assignment-batch-service/Chart.yaml
src/test/java/uk/gov/hmcts/reform/roleassignmentbatch/helper/TestDataBuilder.java

CVE fix for spring-security
```
[ ] Yes
[X ] No
```

cve fix for spring-security

---

config/owasp/suppressions.xml

https://tools.hmcts.net/jira/browse/AM-2279
```
[ ] Yes
[X] No
```

RAS batch:Fix AM Nightly build failures due to CVE issues

---

charts/am-role-assignment-batch-service/Chart.yaml

https://tools.hmcts.net/jira/browse/AM-2289
```
[ ] Yes
[X] No
```

RAS Batch:java version in helm repo version update

---

build.gradle

https://tools.hmcts.net/jira/browse/AM-2291
```
[ ] Yes
[X] No
```

RAS Batch:Merge renovate bot pr's

---

build.gradle
infrastructure/terraform.tf

https://tools.hmcts.net/jira/browse/AM-2291
```
[ ] Yes
[X] No
```

RAS:BatchMerge renovate bot pr's

---

config/owasp/suppressions.xml

https://tools.hmcts.net/jira/browse/AM-2343

AM-2343 Suppressing LD SnakeYaml CVE

---

src/main/resources/application.yaml

Setting two years to delete expired records
```
[ ] Yes
[X ] No
```

expiry records deletion for JBS

---

build.gradle

https://tools.hmcts.net/jira/browse/AM-2404
```
[ ] Yes
[X] No
```

CVE-2021-43980

---

src/main/java/uk/gov/hmcts/reform/roleassignmentbatch/config/BatchConfig.java

missing default flag
```
[ ] Yes
[ X] No
```

master flag to default

---

charts/am-role-assignment-batch-service/Chart.yaml
charts/am-role-assignment-batch-service/values.yaml

enable jbs db
```
[ ] Yes
[ X] No
```

jbs config

---

build.gradle

https://tools.hmcts.net/jira/browse/AM-2434

Update spring security version

---

build.gradle
charts/am-role-assignment-batch-service/values.preview.template.yaml

fortify scan fix
```
[ ] Yes
[X ] No
```

Am fortify fix

---

charts/am-role-assignment-batch-service/Chart.yaml

https://tools.hmcts.net/jira/browse/AM-2589
```
[ ] Yes
[X] No
```

AKS Job version upgrade

---

build.gradle

Dependency Check

---

infrastructure/variables.tf

infra deprecate update
```
[ ] Yes
[X ] No
```

infra depricate update

---

build.gradle
config/owasp/suppressions.xml
src/integrationTest/resources/application-test.yaml
src/main/resources/application.yaml

https://tools.hmcts.net/jira/browse/AM-2517
```
[ ] Yes
[x] No
```

Springboot upgrade 2.7.7

---

config/owasp/suppressions.xml

https://tools.hmcts.net/jira/browse/AM-2668
```
[ ] Yes
[X] No
```

RAS Batch:Application Nightly build failed due to CVE-2022-45688

---

Jenkinsfile_CNP
build.gradle

Spring boot compatible version
```
[ ] Yes
[X ] No
```

compatable jar version for spring boot

---

build.gradle
charts/am-role-assignment-batch-service/Chart.yaml
config/owasp/suppressions.xml

https://tools.hmcts.net/jira/browse/AM-2520
Cleanup suppression / CVEs
```
[ ] Yes
[ x] No
```

Am 2520 cleanup suppressions

---

charts/am-role-assignment-batch-service/Chart.yaml

https://tools.hmcts.net/jira/browse/AM-2806
```
[ ] Yes
[ *] No
```

AM-2806: Upgrade chart-job version

---

build.gradle
config/owasp/suppressions.xml

https://tools.hmcts.net/jira/browse/AM-2816
tomcat version upgraded to 9.0.74
```
[ ] Yes
[x] No
```

AM-2816 CVE-2023-28709 tomcat version upgraded to 9.0.74

---

config/owasp/suppressions.xml

https://tools.hmcts.net/jira/browse/AM-2890
CVE-2023-38286 Suppression
```
[ ] Yes
[x ] No
```

AM-2890 CVE-2023-38286 Suppression

---

config/owasp/suppressions.xml

https://tools.hmcts.net/jira/browse/AM-2890
CVE-2023-38286 Remove Suppression
```
[ ] Yes
[x] No
```

AM-2890 CVE-2023-38286 Remove Suppression

---

build.gradle
config/owasp/suppressions.xml

https://tools.hmcts.net/jira/browse/AM-2987 CVE-2023-42794
https://tools.hmcts.net/jira/browse/AM-2988 CVE-2023-42795
https://tools.hmcts.net/jira/browse/AM-2989 CVE-2023-45648
tomcat upgrade 9.0.81

AM-2987 tomcat upgrade 9.0.81

---

Jenkinsfile_CNP

https://tools.hmcts.net/jira/browse/AM-2984
Connect to v15 JBS ITHC - Remove 'ithc' from git branchesToSync

AM-2984 Connect to v15 JBS ITHC - Remove 'ithc' from git branchesToSync

---

Jenkinsfile_CNP

https://tools.hmcts.net/jira/browse/AM-2943
v15 Migration Resync ITHC Perftest

AM-2943 v15 Migration Resync ITHC Perftest

---

charts/am-role-assignment-batch-service/Chart.yaml

https://tools.hmcts.net/jira/browse/AM-3055
Bump Helm Job Chart Version to 1.1.5

AM-3055 Bump Helm Job Chart Version to 1.1.5

---

charts/am-role-assignment-batch-service/Chart.yaml

https://tools.hmcts.net/jira/browse/DTSAM-86
Helm chart upgrade - chart-job version to ~2.1.1

DTSAM-86 Helm chart upgrade - chart-job version to ~2.1.1

---

Jenkinsfile_nightly
build.gradle

https://tools.hmcts.net/jira/browse/DTSAM-543
PI Test Review

DTSAM-543 PI Test Review

---

config/owasp/suppressions.xml

[DTSAM-976](https://tools.hmcts.net/jira/browse/DTSAM-976) _"Review CVE suppressions after SB3 + DTSPO-23398"_
Adjust CVE suppressions after SB3 + DTSPO-23398

DTSAM-976 Review CVE suppressions after SB3 + DTSPO-23398
